### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#40]
## Background
About a year ago Mario from Docker contacted us asking if we would consider bringing this into the official images. The community said [yes](https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20160118/000908.html), but Haris and I both got very busy. I'm now working on Swift backend development full time and this is squarely under my remit.

## Why
- Promote adoption of Swift on Docker, and Swift
- Get free security scanning from Docker Hub
- Get support from Docker engineers on best practice engineering of Dockerfile

## How
We need to prepare two pull requests:

1. A documentation pull request [against the docs repo](https://github.com/docker-library/docs), essentially a Markdown file that is the contents of the description on Docker hub (for instance, https://hub.docker.com/_/mongo/)
2. A descriptive pull request [against the library repo](https://github.com/docker-library/official-images) specifying the available tags and versions for docker hub.

## Todo
- [ ] Mario is apparently no longer with Docker. We should find a counterpart who's willing to champion this inside Docker
- [x] Draft a documentation PR in this repo
- [x] ~Draft an image PR in this repo~ [Fuck it ship it](https://github.com/docker-library/official-images/pull/2500)

**Comment by hamin** [comment]
@swizzlr let's make this priority. I'll try to document some stuff I found when looking at this last year. I was particularly looking at the official redis image. And was swinging how they were breaking up versions in separate folders. Not exactly sure how this would work for us.

**Comment by swizzlr** [comment]
@hamin sounds good. Open a PR with whatever you have. I want this official by the end of the first week of the new year, if possible.

**Comment by swizzlr** [comment]
(I am full of rosato spumante)

**Comment by swizzlr** [comment]
🍸🍾

**Comment by Khalian** [comment]
How about this : https://github.com/Khalian/docs/tree/master/swift

I can send a PR if you think this is good enough for point 1.

**Comment by swizzlr** [comment]
@Khalian that's something to get going with for sure. Can you open that as a PR against _this_ repo, into a subfolder (docs/). We'll review. Once we have it good enough we'll open it against the official repo, along with the other PR.

**Comment by Khalian** [comment]
https://github.com/swiftdocker/docker-swift/pull/43

**Comment by swizzlr** [comment]
Booya https://github.com/docker-library/official-images/pull/2500

**Comment by swizzlr** [comment]
Done.
